### ISSUE TITLE
Two Module Locations Incorrect on "The Team"

### ISSUE THREAD

**Issue by XYNdesign** [rockettheme/docs#168]
I believe the Custom HTML modules "Iridescent Demo" and "Sample Contact Info" in the demo are positioned at bottom-a and bottom-b, respectively. The documentation page shows them at footer-a and footer-b.

**Comment by FrugalGeek** [comment]
Good catch. This has been fixed in a recent commit.

**Comment by FrugalGeek** [comment]
You have a good eye. Please feel free to make the changes using the github editor and submit a pull request if you find any more bits and pieces. That way you can get credit for the commit. We're glad you find the documentation useful, and hope you enjoy Iridescent.

**Comment by XYNdesign** [comment]
Thanks. Brand new to GitHub. Guess I'll have to learn how to use it. ;-)
