### ISSUE TITLE
"Services" Example Page Shows Incorrect Breadcrumbs Module Suffix

### ISSUE THREAD

**Issue by XYNdesign** [rockettheme/docs#171]
I'm not being picky; honest. I'm going through documentation of a new install and figure if I see a discrepancy, you'd want to know about it.

On the documentation for the "Services" demo page it shows the Breadcrumbs Module Class Suffix as: hidden-phone nomarginall medpaddingtop medpaddingbottom.

In the RocketLauncher installation, there is only one Breadcrumbs module, and the only Module Class Suffix is hidden-phone.

Thanks for all your work.

**Comment by FrugalGeek** [comment]
Fixed in Commit #172 

https://github.com/rockettheme/docs/commit/7938a8616e0381e8274f92be723a7ebd0b834075

Thanks!
