### ISSUE TITLE
please complete Send mail part description

### ISSUE THREAD

**Issue by zzndino** [rockettheme/docs#211]
Thanks for your contribution! Really nice work, could you finish send mail part description. 
![12](https://cloud.githubusercontent.com/assets/805643/7769104/157985aa-00b4-11e5-9f90-0b5589b5cd65.png)

**Comment by FrugalGeek** [comment]
Hello there. Can you provide me with the name of the product you're referencing in particular? We have docs for a lot of contact forms in our demos, I just need to know which one you need. The template/theme name and the platform would work. Thanks!

**Comment by zzndino** [comment]
oh, it's Vermilion

**Comment by FrugalGeek** [comment]
Contact Us page docs are up for Vermillion. Essentially, the info in the contact us form is sourced from a `template-contact.php` file included with the theme.
