### ISSUE TITLE
Site for post bugs of rockettheme extensions?

### ISSUE THREAD

**Issue by AbeAlpha** [rockettheme/docs#212]
I find a bug in roksprocket. Where i can post it?

**Comment by FrugalGeek** [comment]
The RocketTheme forum is the best place. http://rockettheme.com/forum

**Comment by FrugalGeek** [comment]
Alternatively, you can reach out via our contact form http://www.rockettheme.com/contact-us. Be as detailed as possible. What happened, screen shots a plus, what CMS, steps to reproduce, etc. Thanks a bunch!

**Comment by AbeAlpha** [comment]
the problem is I have no money to pay a subscription TT but good to know the form.
Why not put all RocketTheme on github for some more advanced users?

**Comment by mahagr** [comment]
If you didn't notice already, RocketTheme is already in GitHub, just the old and commercial products aren't there.

Right now there are no plans to move the existing products to GitHub.
