### ISSUE TITLE
Extend info on "How to install a Joomla template"

### ISSUE THREAD

**Issue by kat05** [rockettheme/docs#256]
http://www.rockettheme.com/docs/joomla/platform/templates.md#how-to-install-a-joomla-template

The info mentions the Standalone and Bundle options, which is correct for Gantry 4 templates.
I think we need to extend the info for Gantry 5 templates now, as there is no more Bundle option.

**Comment by FrugalGeek** [comment]
Added the Gantry 5 template installation guide to the Gantry 5 section and moved the Gantry 4 guide to the Gantry 4 section from General.
