### ISSUE TITLE
Callisto Mainfeature/Main CSS class incorrect from Callisto 1.2.0

### ISSUE THREAD

**Issue by muffindcc** [rockettheme/docs#261]
In the upcoming 1.2.0 update of Callisto, the nopaddingall class is being replaced with fp-contentlist. This needs to be reflected in the docs (including images).

**Comment by FrugalGeek** [comment]
Our demo is on 1.3.0 and we're still using `nopaddingall` in the CSS classes locations. Is this intentional, or did we revert back to nopaddingall?
