### ISSUE TITLE
Callisto (WordPress) Proofreading

### ISSUE THREAD

**Issue by FrugalGeek** [rockettheme/docs#262]
## Index.md
- [x] Change WordPress Version Requirement to 4.2
- [x] Update Link to Installation Documentation for Theme
- [x] Add RokCommon Back to Recommented Plugins
- [x] Replace instances of "Template Settings" with "Theme Settings"
- [x] Overrides Need to Be Called Outlines

**Comment by newkind** [comment]
- [ ] Fix the wrong Joomla path to theme settings (Administration -> Components -> Gantry 5 Themes -> Callisto)
- [ ] Change word extensions to plugins EVERYWHERE :)
- [ ] Showcase section should mention placing RokSprocket widget in the widget position and selecting created RokSprocket item in the dropdown
