### ISSUE TITLE
Issue style K2

### ISSUE THREAD

**Issue by adriannx** [rockettheme/docs#280]
Hello the botton save of k2 It is not displayed properly. I have On "
![323](https://cloud.githubusercontent.com/assets/5619504/10325898/f8a2b510-6c5a-11e5-8f5c-966ed37c277d.PNG)

![95](https://cloud.githubusercontent.com/assets/5619504/10325874/dd291a22-6c5a-11e5-876d-545ab4b372f5.PNG)

Please Help!

**Comment by FrugalGeek** [comment]
Terribly sorry, but we aren't able to provide support via GitHub. Best place to get support are the official RocketTheme support forums. http://rockettheme.com/forum
