### ISSUE TITLE
RockSpRoket Version 2.1.12 image link error

### ISSUE THREAD

**Issue by hollyboom** [rockettheme/docs#346]
Hi Guys,
First thanks for your great job,and for sharing your work.

I have this error:
when i want to set an image in an mozaic from media manager in Version 2.1.12 do not working,stay an blank ajax block and nothink happen.

I have the next configuration: fresh install
Wordpress latest,
Gantry 5.2.13
installed the rockcommom
and RockSpRocket Version 2.1.12....the latest one .

Thanks fo all.Best regards.

**Comment by FrugalGeek** [comment]
Closing this one because it isn't a documentation issue. Have made the development team aware, however. The best place to submit errors is either through RocketTheme's forums or contact page. http://rockettheme.com/contact-us

**Comment by hollyboom** [comment]
Thanks
