### ISSUE TITLE
Text mixed up

### ISSUE THREAD

**Issue by lapausecafe** [rockettheme/docs#498]
On top of the page it is written:

"To accomplish this, you will want to follow these steps:

(...)

Navigate to the Features tab."

Later, it is written:

"Note: Some templates have this option under the Features tab rather than Style."

This is mixed up.

The last line should say:

""Note: Some templates have this option under the Style tab rather than Features."

**Comment by RyanMPierson** [comment]
Fixed in 5eaa019
